name: Sync Repository to GitLab

on:
  push

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout all history
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Sync to GitLab
      uses: keninkujovic/gitlab-sync@2.1.0
      with:
        gitlab_url: ${{ secrets.GITLAB_URL }}
        username: ${{ secrets.GITLAB_USERNAME }}
        gitlab_pat: ${{ secrets.GITLAB_PAT }}